import Config

# Configure your database
config :token_guard, TokenGuard.Repo,
  username: "postgres",
  password: "postgres",
  hostname: "localhost",
  database: "token_guard_dev",
  stacktrace: true,
  show_sensitive_data_on_connection_error: true,
  pool_size: 10

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :token_guard, TokenGuardWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}],
  check_origin: false,
  code_reloader: true,
  debug_errors: true,
  secret_key_base: "zP2mgut6CnP0fGGz9BoTkSkzH2c+UIqSUn26QRaIX8uOJlXeSNj2t+oBen04AQE7",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:token_guard, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:token_guard, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Reload browser tabs when matching files change.
config :token_guard, TokenGuardWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns: [
      # Static assets, except user uploads
      ~r"priv/static/(?!uploads/).*\.(js|css|png|jpeg|jpg|gif|svg)$"E,
      # Gettext translations
      ~r"priv/gettext/.*\.po$"E,
      # Router, Controllers, LiveViews and LiveComponents
      ~r"lib/token_guard_web/router\.ex$"E,
      ~r"lib/token_guard_web/(controllers|live|components)/.*\.(ex|heex)$"E
    ]
  ]

# Enable LiveDashboard in development
config :token_guard, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# Oban config
config :token_guard, Oban,
  repo: TokenGuard.Repo,
  plugins: [
    {Oban.Plugins.Cron, crontab: [{"* * * * *", TokenGuard.Workers.ExpiredTokenReleaser}]}
  ],
  queues: [default: 10]

config :token_guard, start_oban: true
