name: CI Tests

on:
  push:
    branches:
      - master
      - release/*
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-24.04
    name: Elixir ${{matrix.elixir}} OTP ${{matrix.otp}}
    strategy:
      fail-fast: false
      matrix:
        otp: [27.3]
        elixir: [1.19.5]

    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{matrix.otp}}
          elixir-version: ${{matrix.elixir}}

      - run: mix deps.get
      - run: mix deps.compile
      - run: mix compile --warnings-as-errors
      - run: mix test